name: Analyse EMA

on:
  schedule:
    - cron: '0 20 * * *' # Planification quotidienne à 20h (UTC)
  workflow_dispatch: # Permet aussi d'exécuter manuellement le workflow

jobs:
  analysis:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run analysis
        run: python scripts/EMA_Git.py

      - name: Vérifier la présence du fichier
        run: |
          ls -l docs/index.html

      - name: Commit and push index.html to gh-pages branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add docs/index.html
          git commit -m "Ajout de index.html"
          git fetch origin gh-pages
          git merge origin/gh-pages --no-edit  # Merge les changements distants de gh-pages
          git push origin HEAD:gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
