name: Analyse EMA

on:
  schedule:
    - cron: '0 20 * * *' # Planification quotidienne à 20h (UTC)
  workflow_dispatch: # Permet aussi d'exécuter manuellement le workflow

jobs:
  analysis:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run analysis
        run: python scripts/EMA_Git.py

      - name: Verify output file
        run: |
          if [ ! -f "output/results.html" ]; then
            echo "Error: output/results.html not found!"
            exit 1

      - name: Move output to docs
        run: |
          mkdir -p docs
          mv output/* docs/

  deploy:
    needs: analysis
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          publish_branch: gh-pages
