name: Analyse EMA et déploiement

on:
  push:
    branches:
      - main # Déclenchement sur la branche "main"
  workflow_dispatch: # Permet d'exécuter le workflow manuellement

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Vérification du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      # Étape 3 : Installation des dépendances
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance openpyxl

      # Étape 4 : Exécution du script Python
      - name: EMA_Git.py
        run: |
          mkdir -p docs
          python your_script.py # Remplacez par le nom de votre fichier Python

      # Étape 5 : Validation du fichier de sortie
      - name: Validate output
        run: |
          if [ ! -f docs/index.html ]; then
            echo "Le fichier index.html est introuvable. Vérifiez le script."
            exit 1
          fi

      # Étape 6 : Déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs # Répertoire contenant le fichier généré
          publish_branch: gh-pages # Branche dédiée pour GitHub Pages
